aws_dbt_snowflake_project:
  outputs:
    dev:
      account: **************
      database: snowflake_dbt_db
      password: *************
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: ...
      type: snowflake
      user: deekshha
      warehouse: ......
  target: dev
